# Matrix Diagonlization

Example of a diagonlization of a matrix to obtain the eigenvalues and eigenvectors using python and numpy.

**This is run in Jupyter notebook were you can run python commands in cells. You need to run through the cells step by step. You can change cells and re-run them, but then you need to re-run also all subsequent cells**

## Import packages
We first need to import the numpy package 

In [1]:
import numpy

## Define Matrix
Then we need to define the matrix to be diagonlization. Here we are using the example from 9E.1 in Atkins' for butadiene. 

The matrix is set up row by row. 

**This is the part that you will need to change.**

In [5]:
B=numpy.array(
    [
    [0,  1,  0,  0],
    [1,  0,  1,  0],
    [0,  1,  0,  1],
    [0,  0,  1,  0]
    ]
    )

print("Matrix to be diagonlized:")    
print(B)
print("")  

Matrix to be diagonlized:
[[0 1 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 1 0]]



## Calculate Eigenvalues and Eigenvectors

We then obtain the eigenvalues and eigenvectors using the [numpy.linalg.eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html) function from numpy. 
 
This function outputs the eigenvalues and eigenvectors in two arrays:
- eigenvectors is the matrix that diagonlized the B mmatrix
- eigenvector[:,i] is the eigenvector corresponding to the eigenvalue in eigenvalues[i]

In [6]:
[eigenvalues,eigenvectors]=numpy.linalg.eig(B)

print("Eigenvalues:")
for e in eigenvalues:
    print("  {:6.4f}".format(e))
print("")

print("Eigenvector matrix:")
print(eigenvectors)
print("")

Eigenvalues:
  -1.6180
  -0.6180
  1.6180
  0.6180

Eigenvector matrix:
[[ 0.37174803  0.60150096 -0.37174803 -0.60150096]
 [-0.60150096 -0.37174803 -0.60150096 -0.37174803]
 [ 0.60150096 -0.37174803 -0.60150096  0.37174803]
 [-0.37174803  0.60150096 -0.37174803  0.60150096]]



**Note that the eigenvalues and eigenvectors are in a different order as compared to the example in the book.**

**Note that the eigenvalues (and corresponding eigenvectors) are not ordered. Thus you need to order them yourself, e.g, from the highest to the lowest** 

We then output the result is nicer formating

In [4]:
print("Eigenvectors")
print("")
for i in range(eigenvalues.size):
    print("Eigenvector corresponding to eigenvalue {:6.4f}".format(eigenvalues[i]))
    print(eigenvectors[:,i])
    print("")

Eigenvectors

Eigenvector corresponding to eigenvalue -1.0931
[-0.50300449  0.54981628 -0.64779637  0.15826684]

Eigenvector corresponding to eigenvalue -0.1446
[-0.74793618  0.10818832  0.62409851 -0.19846364]

Eigenvector corresponding to eigenvalue 1.8883
[ 0.43050565  0.81291804  0.29159852 -0.26229648]

Eigenvector corresponding to eigenvalue 3.3494
[0.04735857 0.15862408 0.32531711 0.9310018 ]

